# Generated by Django 6.0.7 on 2026-07-27 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('monthly_income', models.CharField(max_length=50)),
                ('experience_with_pets', models.TextField(help_text='Describe your previous experience with pets')),
                ('house_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Bungalow', 'Bungalow'), ('Other', 'Other')], max_length=20)),
                ('is_rental', models.BooleanField(default=False, verbose_name='Is it a rental property?')),
                ('family_members', models.PositiveIntegerField(help_text='Number of people in household')),
                ('reason_for_adoption', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('government_id', models.ImageField(help_text='Upload Govt ID (Aadhar/Voter ID)', upload_to='id_proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_requests', to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='dogs.dog')),
            ],
        ),
    ]
