# Generated by Django 6.0.7 on 2026-07-30 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('monthly_income', models.CharField(max_length=50)),
                ('experience_with_pets', models.TextField(help_text='Describe your previous experience with pets')),
                ('house_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Bungalow', 'Bungalow'), ('Other', 'Other')], max_length=20)),
                ('is_rental', models.BooleanField(default=False, verbose_name='Is it a rental property?')),
                ('family_members', models.PositiveIntegerField(help_text='Number of people in household')),
                ('reason_for_adoption', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('government_id', models.ImageField(help_text='Upload Govt ID (Aadhar/Voter ID)', upload_to='id_proofs/')),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Adoption Completed')], default='Pending', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('rejection_details', models.TextField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_requests', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='dogs.dog')),
            ],
        ),
        migrations.CreateModel(
            name='FinalAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateTimeField(auto_now_add=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dogs.dog')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoptions_witnessed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
