# Generated by Django 6.0.7 on 2026-07-27 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(default='Indie / Unknown', max_length=100)),
                ('age', models.CharField(choices=[('Puppy', 'Puppy (0-1 year)'), ('Young', 'Young (1-3 years)'), ('Adult', 'Adult (3-7 years)'), ('Senior', 'Senior (7+ years)')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('vaccinated', models.BooleanField(default=False)),
                ('sterilized', models.BooleanField(default=False)),
                ('health_condition', models.TextField(blank=True, help_text='Any medical history or current health status')),
                ('friendly_with_kids', models.BooleanField(default=True)),
                ('friendly_with_dogs', models.BooleanField(default=True)),
                ('friendly_with_cats', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('location', models.CharField(help_text='Specific area or street', max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_dogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dog_gallery/')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dogs.dog')),
            ],
        ),
    ]
