# Generated by Django 6.0.7 on 2026-07-27 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.CharField(choices=[('Puppy', 'Puppy'), ('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dog',
            name='health_condition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favored_by', to='dogs.dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'dog')},
            },
        ),
    ]
